name: weather
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_screenutil: ^5.9.0
  geocoding: ^2.1.0
  geolocator: ^10.0.1
  get: ^4.6.6
  http: ^1.1.0
  icons_launcher: ^2.1.3
  intl: ^0.18.1
  latlong2: ^0.9.0
  lottie: ^2.6.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
# flutter pub run change_app_package_name:main com.amadytech.weatherapp
# flutter pub get
# dart run icons_launcher:create
icons_launcher:
  image_path: "assets/images/weather.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/ic_launcher.png"
  background_image: "assets/images/background_ic_launcher.png"
  branding: "assets/images/background_ic_launcher.png"
  color_dark: "#121212"
  # color_dark: "#ffffff"
  image_dark: "assets/images/ic_launcher.png"
  branding_dark: "assets/images/background_ic_launcher.png"
  android_12:
    image: "assets/images/ic_launcher.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/ic_launcher.png"
    icon_background_color_dark: "#121212"
  android_gravity: center
  web_image_mode: center
  ios_content_mode: center
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
